// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package favorite_test

import (
	"wongnok/internal/model"

	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIHandler creates a new instance of MockIHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIHandler {
	mock := &MockIHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIHandler is an autogenerated mock type for the IHandler type
type MockIHandler struct {
	mock.Mock
}

type MockIHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIHandler) EXPECT() *MockIHandler_Expecter {
	return &MockIHandler_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Create(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIHandler_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Create(ctx interface{}) *MockIHandler_Create_Call {
	return &MockIHandler_Create_Call{Call: _e.mock.On("Create", ctx)}
}

func (_c *MockIHandler_Create_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Create_Call) Return() *MockIHandler_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Create_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Delete(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIHandler_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Delete(ctx interface{}) *MockIHandler_Delete_Call {
	return &MockIHandler_Delete_Call{Call: _e.mock.On("Delete", ctx)}
}

func (_c *MockIHandler_Delete_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Delete_Call) Return() *MockIHandler_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Delete_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Delete_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Get(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIHandler_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Get(ctx interface{}) *MockIHandler_Get_Call {
	return &MockIHandler_Get_Call{Call: _e.mock.On("Get", ctx)}
}

func (_c *MockIHandler_Get_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Get_Call) Return() *MockIHandler_Get_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Get_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Get_Call {
	_c.Run(run)
	return _c
}

// GetByUser provides a mock function for the type MockIHandler
func (_mock *MockIHandler) GetByUser(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIHandler_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) GetByUser(ctx interface{}) *MockIHandler_GetByUser_Call {
	return &MockIHandler_GetByUser_Call{Call: _e.mock.On("GetByUser", ctx)}
}

func (_c *MockIHandler_GetByUser_Call) Run(run func(ctx *gin.Context)) *MockIHandler_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_GetByUser_Call) Return() *MockIHandler_GetByUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_GetByUser_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_GetByUser_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function for the type MockIHandler
func (_mock *MockIHandler) Update(ctx *gin.Context) {
	_mock.Called(ctx)
	return
}

// MockIHandler_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIHandler_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx *gin.Context
func (_e *MockIHandler_Expecter) Update(ctx interface{}) *MockIHandler_Update_Call {
	return &MockIHandler_Update_Call{Call: _e.mock.On("Update", ctx)}
}

func (_c *MockIHandler_Update_Call) Run(run func(ctx *gin.Context)) *MockIHandler_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIHandler_Update_Call) Return() *MockIHandler_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIHandler_Update_Call) RunAndReturn(run func(ctx *gin.Context)) *MockIHandler_Update_Call {
	_c.Run(run)
	return _c
}

// NewMockIRepository creates a new instance of MockIRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIRepository {
	mock := &MockIRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIRepository is an autogenerated mock type for the IRepository type
type MockIRepository struct {
	mock.Mock
}

type MockIRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIRepository) EXPECT() *MockIRepository_Expecter {
	return &MockIRepository_Expecter{mock: &_m.Mock}
}

// Count provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Count(UserID string, search string) (int64, error) {
	ret := _mock.Called(UserID, search)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (int64, error)); ok {
		return returnFunc(UserID, search)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) int64); ok {
		r0 = returnFunc(UserID, search)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(UserID, search)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockIRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - UserID string
//   - search string
func (_e *MockIRepository_Expecter) Count(UserID interface{}, search interface{}) *MockIRepository_Count_Call {
	return &MockIRepository_Count_Call{Call: _e.mock.On("Count", UserID, search)}
}

func (_c *MockIRepository_Count_Call) Run(run func(UserID string, search string)) *MockIRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_Count_Call) Return(n int64, err error) *MockIRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockIRepository_Count_Call) RunAndReturn(run func(UserID string, search string) (int64, error)) *MockIRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Create(favorite *model.Favorite) error {
	ret := _mock.Called(favorite)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Favorite) error); ok {
		r0 = returnFunc(favorite)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - favorite *model.Favorite
func (_e *MockIRepository_Expecter) Create(favorite interface{}) *MockIRepository_Create_Call {
	return &MockIRepository_Create_Call{Call: _e.mock.On("Create", favorite)}
}

func (_c *MockIRepository_Create_Call) Run(run func(favorite *model.Favorite)) *MockIRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.Favorite
		if args[0] != nil {
			arg0 = args[0].(*model.Favorite)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Create_Call) Return(err error) *MockIRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Create_Call) RunAndReturn(run func(favorite *model.Favorite) error) *MockIRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Delete(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
func (_e *MockIRepository_Expecter) Delete(id interface{}) *MockIRepository_Delete_Call {
	return &MockIRepository_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockIRepository_Delete_Call) Run(run func(id int)) *MockIRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Delete_Call) Return(err error) *MockIRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Delete_Call) RunAndReturn(run func(id int) error) *MockIRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Get(userID string) (model.Favorites, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Favorites
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Favorites, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Favorites); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Favorites)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *MockIRepository_Expecter) Get(userID interface{}) *MockIRepository_Get_Call {
	return &MockIRepository_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockIRepository_Get_Call) Run(run func(userID string)) *MockIRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Get_Call) Return(favorites model.Favorites, err error) *MockIRepository_Get_Call {
	_c.Call.Return(favorites, err)
	return _c
}

func (_c *MockIRepository_Get_Call) RunAndReturn(run func(userID string) (model.Favorites, error)) *MockIRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetByID(id int, claimsID string) (model.Favorite, error) {
	ret := _mock.Called(id, claimsID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.Favorite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) (model.Favorite, error)); ok {
		return returnFunc(id, claimsID)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) model.Favorite); ok {
		r0 = returnFunc(id, claimsID)
	} else {
		r0 = ret.Get(0).(model.Favorite)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(id, claimsID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - id int
//   - claimsID string
func (_e *MockIRepository_Expecter) GetByID(id interface{}, claimsID interface{}) *MockIRepository_GetByID_Call {
	return &MockIRepository_GetByID_Call{Call: _e.mock.On("GetByID", id, claimsID)}
}

func (_c *MockIRepository_GetByID_Call) Run(run func(id int, claimsID string)) *MockIRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetByID_Call) Return(favorite model.Favorite, err error) *MockIRepository_GetByID_Call {
	_c.Call.Return(favorite, err)
	return _c
}

func (_c *MockIRepository_GetByID_Call) RunAndReturn(run func(id int, claimsID string) (model.Favorite, error)) *MockIRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetByUser(foodRecipeQuery model.FoodRecipeQuery, userID string) (model.FoodRecipes, error) {
	ret := _mock.Called(foodRecipeQuery, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 model.FoodRecipes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.FoodRecipeQuery, string) (model.FoodRecipes, error)); ok {
		return returnFunc(foodRecipeQuery, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(model.FoodRecipeQuery, string) model.FoodRecipes); ok {
		r0 = returnFunc(foodRecipeQuery, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.FoodRecipeQuery, string) error); ok {
		r1 = returnFunc(foodRecipeQuery, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIRepository_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - foodRecipeQuery model.FoodRecipeQuery
//   - userID string
func (_e *MockIRepository_Expecter) GetByUser(foodRecipeQuery interface{}, userID interface{}) *MockIRepository_GetByUser_Call {
	return &MockIRepository_GetByUser_Call{Call: _e.mock.On("GetByUser", foodRecipeQuery, userID)}
}

func (_c *MockIRepository_GetByUser_Call) Run(run func(foodRecipeQuery model.FoodRecipeQuery, userID string)) *MockIRepository_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.FoodRecipeQuery
		if args[0] != nil {
			arg0 = args[0].(model.FoodRecipeQuery)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetByUser_Call) Return(foodRecipes model.FoodRecipes, err error) *MockIRepository_GetByUser_Call {
	_c.Call.Return(foodRecipes, err)
	return _c
}

func (_c *MockIRepository_GetByUser_Call) RunAndReturn(run func(foodRecipeQuery model.FoodRecipeQuery, userID string) (model.FoodRecipes, error)) *MockIRepository_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeleteByID provides a mock function for the type MockIRepository
func (_mock *MockIRepository) GetDeleteByID(id int, claimsID string) (model.Favorite, error) {
	ret := _mock.Called(id, claimsID)

	if len(ret) == 0 {
		panic("no return value specified for GetDeleteByID")
	}

	var r0 model.Favorite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string) (model.Favorite, error)); ok {
		return returnFunc(id, claimsID)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string) model.Favorite); ok {
		r0 = returnFunc(id, claimsID)
	} else {
		r0 = ret.Get(0).(model.Favorite)
	}
	if returnFunc, ok := ret.Get(1).(func(int, string) error); ok {
		r1 = returnFunc(id, claimsID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIRepository_GetDeleteByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeleteByID'
type MockIRepository_GetDeleteByID_Call struct {
	*mock.Call
}

// GetDeleteByID is a helper method to define mock.On call
//   - id int
//   - claimsID string
func (_e *MockIRepository_Expecter) GetDeleteByID(id interface{}, claimsID interface{}) *MockIRepository_GetDeleteByID_Call {
	return &MockIRepository_GetDeleteByID_Call{Call: _e.mock.On("GetDeleteByID", id, claimsID)}
}

func (_c *MockIRepository_GetDeleteByID_Call) Run(run func(id int, claimsID string)) *MockIRepository_GetDeleteByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIRepository_GetDeleteByID_Call) Return(favorite model.Favorite, err error) *MockIRepository_GetDeleteByID_Call {
	_c.Call.Return(favorite, err)
	return _c
}

func (_c *MockIRepository_GetDeleteByID_Call) RunAndReturn(run func(id int, claimsID string) (model.Favorite, error)) *MockIRepository_GetDeleteByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIRepository
func (_mock *MockIRepository) Update(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - id int
func (_e *MockIRepository_Expecter) Update(id interface{}) *MockIRepository_Update_Call {
	return &MockIRepository_Update_Call{Call: _e.mock.On("Update", id)}
}

func (_c *MockIRepository_Update_Call) Run(run func(id int)) *MockIRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIRepository_Update_Call) Return(err error) *MockIRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIRepository_Update_Call) RunAndReturn(run func(id int) error) *MockIRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIUserService creates a new instance of MockIUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIUserService {
	mock := &MockIUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIUserService is an autogenerated mock type for the IUserService type
type MockIUserService struct {
	mock.Mock
}

type MockIUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIUserService) EXPECT() *MockIUserService_Expecter {
	return &MockIUserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIUserService
func (_mock *MockIUserService) Create(claims model.Claims) (model.User, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIUserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) Create(claims interface{}) *MockIUserService_Create_Call {
	return &MockIUserService_Create_Call{Call: _e.mock.On("Create", claims)}
}

func (_c *MockIUserService_Create_Call) Run(run func(claims model.Claims)) *MockIUserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_Create_Call) Return(user model.User, err error) *MockIUserService_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_Create_Call) RunAndReturn(run func(claims model.Claims) (model.User, error)) *MockIUserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockIUserService
func (_mock *MockIUserService) GetByID(claims model.Claims) (model.User, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockIUserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetByID(claims interface{}) *MockIUserService_GetByID_Call {
	return &MockIUserService_GetByID_Call{Call: _e.mock.On("GetByID", claims)}
}

func (_c *MockIUserService_GetByID_Call) Run(run func(claims model.Claims)) *MockIUserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_GetByID_Call) Return(user model.User, err error) *MockIUserService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_GetByID_Call) RunAndReturn(run func(claims model.Claims) (model.User, error)) *MockIUserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecipes provides a mock function for the type MockIUserService
func (_mock *MockIUserService) GetRecipes(userID string, claims model.Claims) (model.FoodRecipes, error) {
	ret := _mock.Called(userID, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetRecipes")
	}

	var r0 model.FoodRecipes
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, model.Claims) (model.FoodRecipes, error)); ok {
		return returnFunc(userID, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(string, model.Claims) model.FoodRecipes); ok {
		r0 = returnFunc(userID, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, model.Claims) error); ok {
		r1 = returnFunc(userID, claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_GetRecipes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecipes'
type MockIUserService_GetRecipes_Call struct {
	*mock.Call
}

// GetRecipes is a helper method to define mock.On call
//   - userID string
//   - claims model.Claims
func (_e *MockIUserService_Expecter) GetRecipes(userID interface{}, claims interface{}) *MockIUserService_GetRecipes_Call {
	return &MockIUserService_GetRecipes_Call{Call: _e.mock.On("GetRecipes", userID, claims)}
}

func (_c *MockIUserService_GetRecipes_Call) Run(run func(userID string, claims model.Claims)) *MockIUserService_GetRecipes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) Return(foodRecipes model.FoodRecipes, err error) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(foodRecipes, err)
	return _c
}

func (_c *MockIUserService_GetRecipes_Call) RunAndReturn(run func(userID string, claims model.Claims) (model.FoodRecipes, error)) *MockIUserService_GetRecipes_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockIUserService
func (_mock *MockIUserService) Update(user *model.User) (model.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*model.User) (model.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*model.User) model.User); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(*model.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockIUserService_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - user *model.User
func (_e *MockIUserService_Expecter) Update(user interface{}) *MockIUserService_Update_Call {
	return &MockIUserService_Update_Call{Call: _e.mock.On("Update", user)}
}

func (_c *MockIUserService_Update_Call) Run(run func(user *model.User)) *MockIUserService_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *model.User
		if args[0] != nil {
			arg0 = args[0].(*model.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_Update_Call) Return(user1 model.User, err error) *MockIUserService_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockIUserService_Update_Call) RunAndReturn(run func(user *model.User) (model.User, error)) *MockIUserService_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertWithClaims provides a mock function for the type MockIUserService
func (_mock *MockIUserService) UpsertWithClaims(claims model.Claims) (model.User, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for UpsertWithClaims")
	}

	var r0 model.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(model.Claims) (model.User, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.Claims) model.User); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(model.User)
	}
	if returnFunc, ok := ret.Get(1).(func(model.Claims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIUserService_UpsertWithClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertWithClaims'
type MockIUserService_UpsertWithClaims_Call struct {
	*mock.Call
}

// UpsertWithClaims is a helper method to define mock.On call
//   - claims model.Claims
func (_e *MockIUserService_Expecter) UpsertWithClaims(claims interface{}) *MockIUserService_UpsertWithClaims_Call {
	return &MockIUserService_UpsertWithClaims_Call{Call: _e.mock.On("UpsertWithClaims", claims)}
}

func (_c *MockIUserService_UpsertWithClaims_Call) Run(run func(claims model.Claims)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.Claims
		if args[0] != nil {
			arg0 = args[0].(model.Claims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) Return(user model.User, err error) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockIUserService_UpsertWithClaims_Call) RunAndReturn(run func(claims model.Claims) (model.User, error)) *MockIUserService_UpsertWithClaims_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIService creates a new instance of MockIService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIService {
	mock := &MockIService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIService is an autogenerated mock type for the IService type
type MockIService struct {
	mock.Mock
}

type MockIService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIService) EXPECT() *MockIService_Expecter {
	return &MockIService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockIService
func (_mock *MockIService) Create(id int, claims model.Claims) (model.Favorite, error) {
	ret := _mock.Called(id, claims)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 model.Favorite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, model.Claims) (model.Favorite, error)); ok {
		return returnFunc(id, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(int, model.Claims) model.Favorite); ok {
		r0 = returnFunc(id, claims)
	} else {
		r0 = ret.Get(0).(model.Favorite)
	}
	if returnFunc, ok := ret.Get(1).(func(int, model.Claims) error); ok {
		r1 = returnFunc(id, claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockIService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - id int
//   - claims model.Claims
func (_e *MockIService_Expecter) Create(id interface{}, claims interface{}) *MockIService_Create_Call {
	return &MockIService_Create_Call{Call: _e.mock.On("Create", id, claims)}
}

func (_c *MockIService_Create_Call) Run(run func(id int, claims model.Claims)) *MockIService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Create_Call) Return(favorite model.Favorite, err error) *MockIService_Create_Call {
	_c.Call.Return(favorite, err)
	return _c
}

func (_c *MockIService_Create_Call) RunAndReturn(run func(id int, claims model.Claims) (model.Favorite, error)) *MockIService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockIService
func (_mock *MockIService) Delete(id int, claims model.Claims) error {
	ret := _mock.Called(id, claims)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, model.Claims) error); ok {
		r0 = returnFunc(id, claims)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockIService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int
//   - claims model.Claims
func (_e *MockIService_Expecter) Delete(id interface{}, claims interface{}) *MockIService_Delete_Call {
	return &MockIService_Delete_Call{Call: _e.mock.On("Delete", id, claims)}
}

func (_c *MockIService_Delete_Call) Run(run func(id int, claims model.Claims)) *MockIService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_Delete_Call) Return(err error) *MockIService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIService_Delete_Call) RunAndReturn(run func(id int, claims model.Claims) error) *MockIService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockIService
func (_mock *MockIService) Get(userID string) (model.Favorites, error) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 model.Favorites
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (model.Favorites, error)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) model.Favorites); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Favorites)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockIService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - userID string
func (_e *MockIService_Expecter) Get(userID interface{}) *MockIService_Get_Call {
	return &MockIService_Get_Call{Call: _e.mock.On("Get", userID)}
}

func (_c *MockIService_Get_Call) Run(run func(userID string)) *MockIService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIService_Get_Call) Return(favorites model.Favorites, err error) *MockIService_Get_Call {
	_c.Call.Return(favorites, err)
	return _c
}

func (_c *MockIService_Get_Call) RunAndReturn(run func(userID string) (model.Favorites, error)) *MockIService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUser provides a mock function for the type MockIService
func (_mock *MockIService) GetByUser(foodRecipeQuery model.FoodRecipeQuery, claims model.Claims) (model.FoodRecipes, int64, error) {
	ret := _mock.Called(foodRecipeQuery, claims)

	if len(ret) == 0 {
		panic("no return value specified for GetByUser")
	}

	var r0 model.FoodRecipes
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(model.FoodRecipeQuery, model.Claims) (model.FoodRecipes, int64, error)); ok {
		return returnFunc(foodRecipeQuery, claims)
	}
	if returnFunc, ok := ret.Get(0).(func(model.FoodRecipeQuery, model.Claims) model.FoodRecipes); ok {
		r0 = returnFunc(foodRecipeQuery, claims)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.FoodRecipes)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(model.FoodRecipeQuery, model.Claims) int64); ok {
		r1 = returnFunc(foodRecipeQuery, claims)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(model.FoodRecipeQuery, model.Claims) error); ok {
		r2 = returnFunc(foodRecipeQuery, claims)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIService_GetByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUser'
type MockIService_GetByUser_Call struct {
	*mock.Call
}

// GetByUser is a helper method to define mock.On call
//   - foodRecipeQuery model.FoodRecipeQuery
//   - claims model.Claims
func (_e *MockIService_Expecter) GetByUser(foodRecipeQuery interface{}, claims interface{}) *MockIService_GetByUser_Call {
	return &MockIService_GetByUser_Call{Call: _e.mock.On("GetByUser", foodRecipeQuery, claims)}
}

func (_c *MockIService_GetByUser_Call) Run(run func(foodRecipeQuery model.FoodRecipeQuery, claims model.Claims)) *MockIService_GetByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 model.FoodRecipeQuery
		if args[0] != nil {
			arg0 = args[0].(model.FoodRecipeQuery)
		}
		var arg1 model.Claims
		if args[1] != nil {
			arg1 = args[1].(model.Claims)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIService_GetByUser_Call) Return(foodRecipes model.FoodRecipes, n int64, err error) *MockIService_GetByUser_Call {
	_c.Call.Return(foodRecipes, n, err)
	return _c
}

func (_c *MockIService_GetByUser_Call) RunAndReturn(run func(foodRecipeQuery model.FoodRecipeQuery, claims model.Claims) (model.FoodRecipes, int64, error)) *MockIService_GetByUser_Call {
	_c.Call.Return(run)
	return _c
}
